# Generated by Django 3.2.4 on 2021-06-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210626_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Others', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category', verbose_name='Medicine'),
        ),
    ]
