# Generated by Django 3.2.4 on 2021-12-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dosage',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Others', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
