# Generated by Django 3.2.4 on 2021-12-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211208_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Quiz', 'Quiz'), ('Asignment', 'Assignment'), ('Exam', 'Exam'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
