# Generated by Django 3.2.4 on 2021-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Exam', 'Exam'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
